- name: conditions in yaml
  hosts: local
  connection: local
  vars: 
    number: 5
  tasks: 
    -name : check number is less than 10
    ansible.builtin.debug:
      msg: "number is {{number}} is < than 10"
    when: number < 10