- name: gathering facts in ansible
  hosts: local
  connection: local
  tasks: 
  - name: install nginx if it is redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family=="RedHat"