- name: functions
  hosts: local
  connection: local
  vars: 
    technologies: Devops, Linux, shell, Ansible
    dict:
      Application: payment
      Environment: dev
    list:
      - key: Application
        value: payment
      - key: Environment
        value: dev

  tasks: 
  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{technologies | split(',')}}"

  - name: converting dict to list
    ansible.builtin.debug:
      msg: "{{dict | dict2items }}"

  - name: converting list to dict 
    ansible.builtin.debug:
      msg: "{{ list | items2dict }}"

  - name: read the yaml and store in the variable
    ansible.builtin.set_fact:
      student_yaml: "{{lookup('file','student.yaml') | from_yaml}}"

  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "json:{{ to_json}}"

